# OpenAI secrets
OPENAI_API_KEY = ""

# Astra DB secrets
ASTRA_ENDPOINT = ""
ASTRA_TOKEN = ""

# Optionally: LangSmith secrets for tracing
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_ENDPOINT = ""
LANGCHAIN_API_KEY = ""
LANGCHAIN_PROJECT = ""


[delete_option]
# Follow the rule: username = "delete_option"
# Where delete_option = True allows the 'Delete Context' button to be shown for that username
michel = "True"